// Project files (BUILD_ORDER item 7) — turns generated code into a RUNNABLE project:
// package.json, tsconfig.json, README.md, mcp.json, .env.example, .gitignore.

import type { IR } from "../ir/types.ts";
import { authEnvVar } from "./server-template.ts";

const SDK_VERSION = "^1.0.0"; // pinned in real output; range here for the demo
const ZOD_VERSION = "^3.23.0";

export function kebab(title: string): string {
  return (
    title
      .replace(/[^a-zA-Z0-9]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "")
      .toLowerCase() || "mcp-server"
  );
}

export function packageJson(name: string): string {
  return JSON.stringify(
    {
      name,
      version: "1.0.0",
      private: true,
      type: "module",
      bin: { [name]: "dist/index.js" },
      scripts: { build: "tsc", start: "node dist/index.js" },
      dependencies: { "@modelcontextprotocol/sdk": SDK_VERSION, zod: ZOD_VERSION },
      devDependencies: { typescript: "^5.6.0", "@types/node": "^22.0.0" },
    },
    null,
    2,
  );
}

export function tsconfigJson(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        outDir: "dist",
        strict: true,
        skipLibCheck: true,
        esModuleInterop: true,
      },
      include: ["src"],
    },
    null,
    2,
  );
}

export function envExample(ir: IR): string {
  const lines = [`API_BASE_URL=${ir.baseUrl}`];
  const v = authEnvVar(ir);
  if (v) lines.push(`# Your API credential — keep it secret, never commit .env`);
  if (v) lines.push(`${v}=`);
  return lines.join("\n") + "\n";
}

export function gitignore(): string {
  return ["node_modules", "dist", ".env"].join("\n") + "\n";
}

export function mcpJson(name: string, ir: IR): string {
  const env: Record<string, string> = { API_BASE_URL: ir.baseUrl };
  const v = authEnvVar(ir);
  if (v) env[v] = `\${${v}}`;
  return JSON.stringify({ mcpServers: { [name]: { command: "node", args: [`./${name}/dist/index.js`], env } } }, null, 2);
}

export function readme(name: string, ir: IR): string {
  const v = authEnvVar(ir);
  const toolList = ir.tools.map((t) => `- \`${t.name}\` — ${t.method} ${t.path}`).join("\n");
  return `# ${name}

A Model Context Protocol (MCP) server for **${ir.title}**, generated by MCPForge.

## Tools
${toolList}

## Run it
\`\`\`bash
npm install
cp .env.example .env   # then fill in your values
npm run build
node dist/index.js
\`\`\`

## Add to Claude Desktop
Add this to your Claude Desktop \`mcp.json\` (or merge \`mcp.json\` from this folder):
\`\`\`json
${mcpJson(name, ir)}
\`\`\`
${v ? `\nSet \`${v}\` in your \`.env\` — it is read from the environment and never hard-coded.\n` : ""}
_Generated with MCPForge._
`;
}
