// Code generation (BUILD_ORDER item 5) — IR -> a complete, valid `src/index.ts` MCP server.
// Output: official @modelcontextprotocol/sdk, Zod-validated inputs, auth from env
// (never hard-coded), structured errors, timeouts. This is the core value.

import type { IR, IRParam, IRTool } from "../ir/types.ts";

function zodFor(p: IRParam): string {
  let base: string;
  switch (p.schemaType) {
    case "string": base = "z.string()"; break;
    case "number":
    case "integer": base = "z.number()"; break;
    case "boolean": base = "z.boolean()"; break;
    case "array": base = "z.array(z.any())"; break;
    case "object": base = "z.record(z.string(), z.any())"; break;
    default: base = p.in === "body" ? "z.record(z.string(), z.any())" : "z.any()";
  }
  if (p.description) base += `.describe(${JSON.stringify(p.description.slice(0, 200))})`;
  if (!p.required) base += ".optional()";
  return base;
}

function shapeLiteral(tool: IRTool): string {
  if (tool.params.length === 0) return "{}";
  const fields = tool.params.map((p) => `    ${JSON.stringify(p.name)}: ${zodFor(p)}`);
  return `{\n${fields.join(",\n")}\n  }`;
}

function pathExpr(tool: IRTool): string {
  // /pets/{petId} -> `/pets/${encodeURIComponent(String(args["petId"]))}`
  const interpolated = tool.path.replace(/\{([^}]+)\}/g, (_m, name) => {
    return "${encodeURIComponent(String(args[" + JSON.stringify(name) + "]))}";
  });
  return "`" + interpolated + "`";
}

function authBlocks(ir: IR): { header: string; query: string; envVar: string | null } {
  const s = ir.security;
  if (s.type === "bearer" || s.type === "oauth2") {
    return { header: 'if (TOKEN) headers["Authorization"] = `Bearer ${TOKEN}`;', query: "", envVar: "API_TOKEN" };
  }
  if (s.type === "apiKey" && s.in === "header") {
    return { header: `if (TOKEN) headers[${JSON.stringify(s.name)}] = TOKEN;`, query: "", envVar: "API_KEY" };
  }
  if (s.type === "apiKey" && s.in === "query") {
    return { header: "", query: `if (TOKEN) url.searchParams.set(${JSON.stringify(s.name)}, TOKEN);`, envVar: "API_KEY" };
  }
  return { header: "", query: "", envVar: null };
}

function handlerBody(tool: IRTool, auth: { header: string; query: string }): string {
  const queryParams = tool.params.filter((p) => p.in === "query");
  const hasBody = tool.params.some((p) => p.in === "body");
  const lines: string[] = [];
  lines.push(`    const url = new URL(\`\${BASE}\` + ${pathExpr(tool)});`);
  if (queryParams.length) {
    const entries = queryParams.map((p) => `${JSON.stringify(p.name)}: args[${JSON.stringify(p.name)}]`).join(", ");
    lines.push(`    for (const [k, v] of Object.entries({ ${entries} })) {`);
    lines.push(`      if (v !== undefined && v !== null) url.searchParams.set(k, String(v));`);
    lines.push(`    }`);
  }
  if (auth.query) lines.push(`    ${auth.query}`);
  lines.push(`    const headers: Record<string, string> = {};`);
  if (hasBody) lines.push(`    headers["Content-Type"] = "application/json";`);
  if (auth.header) lines.push(`    ${auth.header}`);
  lines.push(`    const res = await fetch(url, {`);
  lines.push(`      method: ${JSON.stringify(tool.method)},`);
  lines.push(`      headers,`);
  if (hasBody) lines.push(`      body: JSON.stringify(args["body"] ?? {}),`);
  lines.push(`      signal: AbortSignal.timeout(15000),`);
  lines.push(`    });`);
  lines.push(`    const text = await res.text();`);
  lines.push(`    if (!res.ok) {`);
  lines.push(`      return { content: [{ type: "text", text: \`Error \${res.status}: \${text}\` }], isError: true };`);
  lines.push(`    }`);
  lines.push(`    return { content: [{ type: "text", text }] };`);
  return lines.join("\n");
}

export function generateServerCode(ir: IR, serverName: string): string {
  const auth = authBlocks(ir);
  const tools = ir.tools
    .map((tool) => {
      const desc = tool.description ?? tool.summary ?? `${tool.method} ${tool.path}`;
      return (
        `server.tool(\n` +
        `  ${JSON.stringify(tool.name)},\n` +
        `  ${JSON.stringify(desc)},\n` +
        `  ${shapeLiteral(tool)},\n` +
        `  async (args: Record<string, any>) => {\n` +
        `${handlerBody(tool, auth)}\n` +
        `  },\n` +
        `);`
      );
    })
    .join("\n\n");

  const tokenLine = auth.envVar
    ? `const TOKEN = process.env.${auth.envVar}; // from .env — never hard-coded`
    : `// This API requires no authentication.`;

  return `// Generated by MCPForge — an MCP server for ${ir.title}.
// Run: npm install && npm run build && node dist/index.js
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const BASE = process.env.API_BASE_URL ?? ${JSON.stringify(ir.baseUrl)};
${tokenLine}

const server = new McpServer({ name: ${JSON.stringify(serverName)}, version: ${JSON.stringify(ir.version)} });

${tools}

await server.connect(new StdioServerTransport());
`;
}

export function authEnvVar(ir: IR): string | null {
  return authBlocks(ir).envVar;
}
